# -*- coding: utf-8 -*-
"""slushpool data import.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSkA8fh73aoTVnuaak-HNR-9gPO9AZyo
"""

import json
import requests

# create a dictionary for post request
data = dict()

blocks = dict()
slots = [1613676720, 1613728200]
blocks['slots'] = slots

pool = dict()
# for x in range(1613664000, 1613750400, 14400):
# for x in range(1613664000, 1613764800, 14400):
for i in range(11035):
  x = 1613664000 - i * 14400
  temp = dict()
  temp['hashrate_ghps'] = 0
  temp['scoring_ghps'] = 0
  temp['active_workers'] = 0
  temp['active_users'] = 0
  pool[str(x)] = temp
pool['min_used_slot'] = 1

timeSeries = dict()
timeSeries['pool'] = pool

btc = dict()
# btc['last_slot_end'] = 0
# btc['blocks'] = blocks
btc['timeseries_5m'] = timeSeries
# btc['price'] = 0

data['btc'] = btc
# data['time'] = 0
# data['git_head'] = 0
# data['session'] = 0

# print(data)


url = 'https://slushpool.com/api/v1/web/scalar/tree/'
header = dict()
header['content-type'] = 'application/json'
header['accept'] = 'application/json'
header['x-csrftoken'] = 'sWYbkb6rMcPHfiN6Cs1aeUJO0nF17LS0XYTeH7tayuzbDNh4fpgWhXkIb8PGjHmB'
header['origin'] = 'https://slushpool.com'
header['referer'] = 'https://slushpool.com/stats/?c=btc'
# header['cookie'] = 'csrftoken=sWYbkb6rMcPHfiN6Cs1aeUJO0nF17LS0XYTeH7tayuzbDNh4fpgWhXkIb8PGjHmB; _ga=GA1.2.598068749.1597170975; __cfduid=d89828d8521c0749a22842738e75dea471611351016; cf_clearance=424cbcf0671d4b94a0d8410557844d8f6026bd40-1612275211-0-150; sessionid=w345hruq79pasyhc5kwiiefjo3at692a'
header['cookie'] = 'csrftoken=sWYbkb6rMcPHfiN6Cs1aeUJO0nF17LS0XYTeH7tayuzbDNh4fpgWhXkIb8PGjHmB;'
response = requests.post(url, data = json.dumps(data), headers = header)
x = response.json()
result = x['data']['btc']['timeseries_5m']['pool']
print(len(result))
print(result['min_used_slot'])

