# -*- coding: utf-8 -*-
"""slushpool data import.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSkA8fh73aoTVnuaak-HNR-9gPO9AZyo
"""

import json
import requests

# create a dictionary for post request
data = dict()

blocks = dict()
slots = [1613676720, 1613728200]
blocks['slots'] = slots

pool = dict()
# for x in range(1613664000, 1613750400, 14400):
# for x in range(1613664000, 1613764800, 14400):
for i in range(11035):
  x = 1613664000 - i * 14400
  temp = dict()
  temp['hashrate_ghps'] = 0
  temp['scoring_ghps'] = 0
  temp['active_workers'] = 0
  temp['active_users'] = 0
  pool[str(x)] = temp
pool['min_used_slot'] = 1

timeSeries = dict()
timeSeries['pool'] = pool

btc = dict()
# btc['last_slot_end'] = 0
# btc['blocks'] = blocks
btc['timeseries_5m'] = timeSeries
# btc['price'] = 0

data['btc'] = btc
# data['time'] = 0
# data['git_head'] = 0
# data['session'] = 0

# print(data)


url = 'https://slushpool.com'

client = requests.session()
client.get(url)

csrftoken = client.cookies['csrftoken']

data_url = url + "/api/v1/web/scalar/tree/"

header = dict()
header['content-type'] = 'application/json'
header['accept'] = 'application/json'
header['x-csrftoken'] = csrftoken
header['origin'] = url
header['referer'] = url
header['cookie'] = 'csrftoken={0};'.format(csrftoken)
response = client.post(data_url, data=json.dumps(data), headers = header)
x = response.json()
result = x['data']['btc']['timeseries_5m']['pool']

print(result)


