# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.define "192.168.50.50" do |node1|
    node1.vm.box = "bento/ubuntu-20.04"
    node1.vm.network "private_network", ip: "192.168.50.50"
    node1.vm.hostname = "smartminer"
  end
end
