runtime_mode: "REALTIME" # SIMULATION or REALTIME
realtime:
  should_use_api: "True"
  should_fill_empty_db: "True"
  clock_tick_duration: "7.0"
  clock_timestamp_increase_per_tick: "None"
  clock_start_timestamp: "!!timestamp!None"
  analyzer_sleep_duration: "30.0 * MINUTE_SECONDS"
  nice_hash_sleep_duration: "1.0 * MINUTE_SECONDS"
  controller_sleep_duration: "10.0 * MINUTE_SECONDS"
  learner_sleep_duration: "10.0 * MINUTE_SECONDS"
  mine_db_updater_sleep_duration: "7"
  simulation_db_updater_sleep_duration: "1.0 * MINUTE_SECONDS"
  simulation_evaluator_sleep_duration: "1.0 * MINUTE_SECONDS"
  nice_hash_close_orders_before_shutdown: "True"
  learner_always_recreate_model: "False"
  learner_save_model: "True"
  log_level: "logging.INFO"
  log_format: "|||%(asctime)s - %(name)s -  %(levelname)s - %(message)s"
  db_host: "|||127.0.0.1"
  db_port: "|||5432"
  db_user: "|||USERNAME"
  db_password: "|||PASSWORD"
  db_database_name: "|||smart_miner"
  db_simulation_database_name: "|||smart_miner_simulation_data"
  db_csv_data_dir: "|||/home/jamshid/PycharmProjects/smart-miner/files/csv_data/"
  db_csv_separator: "|||,"
simulation:
  clock_tick_duration: "7"
  clock_timestamp_increase_per_tick: "1 * DAY_SECONDS"
  clock_start_timestamp: "!!timestamp!|||04/19/2021-00:00:00"
  simulation_end_timestamp: "!!timestamp!|||04/21/2021-00:00:00"
  log_level: "logging.INFO"
  clean_simulation_database: "False"
  identifier: "|||b_simulation"
  simulation_summaries_data_dir: "|||/home/jamshid/PycharmProjects/smart-miner/files/simulations/"
