MINUTE_SECONDS = 60
HOUR_SECONDS = 60 * MINUTE_SECONDS
DAY_SECONDS = 24 * HOUR_SECONDS
WEEK_SECONDS = 7 * DAY_SECONDS

SLUSHPOOL_NAME = 'slushpool'
SLUSHPOOL_ID = 1
SLUSHPOOL_ID_NICEHASH = 'SLUSHPOOL'
SLUSHPOOL_DATA_FETCH_START_UTC_TIMESTAMP = 1420070400
SLUSHPOOL_API_BASE_URL = 'http://chain.api.btc.com/v3/block/date'

DEFAULT_NUMBER_OF_PAST_BLOCKS_TO_FETCH = 100
DATA_FETCH_API_INTER_DELAY = 30

NICE_HASH_LIMIT_CHANGE_PER_SECOND = 50.0 / (15 * MINUTE_SECONDS)

METRIC_POOL_BLOCK_COUNT_IDENTIFIER = 'pool block count'
METRIC_NETWORK_BLOCK_COUNT_IDENTIFIER = 'network block count'
METRIC_POOL_HASH_POWER_IDENTIFIER = 'pool hash power'
METRIC_NETWORK_HASH_POWER_IDENTIFIER = 'network hash power'
METRIC_POOL_SCORING_HASH_POWER_IDENTIFIER = 'pool scoring hash power'
METRIC_POOL_ACTIVE_USERS_IDENTIFIER = 'pool active users'
METRIC_POOL_ACTIVE_WORKERS_IDENTIFIER = 'pool active workers'
