MINUTE_SECONDS = 60

SLUSHPOOL_NAME = 'slushpool'
SLUSHPOOL_ID = 1

DEFAULT_NUMBER_OF_PAST_BLOCKS_TO_FETCH = 100

NICE_HASH_LIMIT_CHANGE_PER_SECOND = 50.0 / (15 * MINUTE_SECONDS)

METRIC_POOL_BLOCK_COUNT_IDENTIFIER = 'pool block count'
METRIC_NETWORK_BLOCK_COUNT_IDENTIFIER = 'network block count'
METRIC_POOL_HASH_POWER_IDENTIFIER = 'pool hash power'
METRIC_NETWORK_HASH_POWER_IDENTIFIER = 'network hash power'
METRIC_POOL_SCORING_HASH_POWER_IDENTIFIER = 'pool scoring hash power'
METRIC_POOL_ACTIVE_USERS_IDENTIFIER = 'pool active users'
METRIC_POOL_ACTIVE_WORKERS_IDENTIFIER = 'pool active workers'
